//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class HelloTestMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/HelloTest";
        public override string RosMessageName => k_RosMessageName;

        public string hello_message;

        public HelloTestMsg()
        {
            this.hello_message = "";
        }

        public HelloTestMsg(string hello_message)
        {
            this.hello_message = hello_message;
        }

        public static HelloTestMsg Deserialize(MessageDeserializer deserializer) => new HelloTestMsg(deserializer);

        private HelloTestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.hello_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.hello_message);
        }

        public override string ToString()
        {
            return "HelloTestMsg: " +
            "\nhello_message: " + hello_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
