//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class SpotJointMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/SpotJoint";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public float position;
        public float velocity;
        public float acceleration;
        public float load;

        public SpotJointMsg()
        {
            this.name = "";
            this.position = 0.0f;
            this.velocity = 0.0f;
            this.acceleration = 0.0f;
            this.load = 0.0f;
        }

        public SpotJointMsg(string name, float position, float velocity, float acceleration, float load)
        {
            this.name = name;
            this.position = position;
            this.velocity = velocity;
            this.acceleration = acceleration;
            this.load = load;
        }

        public static SpotJointMsg Deserialize(MessageDeserializer deserializer) => new SpotJointMsg(deserializer);

        private SpotJointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.position);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.acceleration);
            deserializer.Read(out this.load);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.position);
            serializer.Write(this.velocity);
            serializer.Write(this.acceleration);
            serializer.Write(this.load);
        }

        public override string ToString()
        {
            return "SpotJointMsg: " +
            "\nname: " + name.ToString() +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nacceleration: " + acceleration.ToString() +
            "\nload: " + load.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
