//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class SpotJointsMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/SpotJoints";
        public override string RosMessageName => k_RosMessageName;

        public SpotJointMsg[] joints;

        public SpotJointsMsg()
        {
            this.joints = new SpotJointMsg[12];
        }

        public SpotJointsMsg(SpotJointMsg[] joints)
        {
            this.joints = joints;
        }

        public static SpotJointsMsg Deserialize(MessageDeserializer deserializer) => new SpotJointsMsg(deserializer);

        private SpotJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, SpotJointMsg.Deserialize, 12);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
        }

        public override string ToString()
        {
            return "SpotJointsMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
