//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TagAndCameraTransformMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TagAndCameraTransform";
        public override string RosMessageName => k_RosMessageName;

        public SpotTransformMsg tag;
        public SpotTransformMsg camera;

        public TagAndCameraTransformMsg()
        {
            this.tag = new SpotTransformMsg();
            this.camera = new SpotTransformMsg();
        }

        public TagAndCameraTransformMsg(SpotTransformMsg tag, SpotTransformMsg camera)
        {
            this.tag = tag;
            this.camera = camera;
        }

        public static TagAndCameraTransformMsg Deserialize(MessageDeserializer deserializer) => new TagAndCameraTransformMsg(deserializer);

        private TagAndCameraTransformMsg(MessageDeserializer deserializer)
        {
            this.tag = SpotTransformMsg.Deserialize(deserializer);
            this.camera = SpotTransformMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.tag);
            serializer.Write(this.camera);
        }

        public override string ToString()
        {
            return "TagAndCameraTransformMsg: " +
            "\ntag: " + tag.ToString() +
            "\ncamera: " + camera.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
