//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class GetSpotCameraResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/GetSpotCamera";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImageMsg image;

        public GetSpotCameraResponse()
        {
            this.image = new Sensor.ImageMsg();
        }

        public GetSpotCameraResponse(Sensor.ImageMsg image)
        {
            this.image = image;
        }

        public static GetSpotCameraResponse Deserialize(MessageDeserializer deserializer) => new GetSpotCameraResponse(deserializer);

        private GetSpotCameraResponse(MessageDeserializer deserializer)
        {
            this.image = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "GetSpotCameraResponse: " +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
