//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class GetSpotCameraRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/GetSpotCamera";
        public override string RosMessageName => k_RosMessageName;

        public string camera_name;
        public string pixel_format;
        public int quality;

        public GetSpotCameraRequest()
        {
            this.camera_name = "";
            this.pixel_format = "";
            this.quality = 0;
        }

        public GetSpotCameraRequest(string camera_name, string pixel_format, int quality)
        {
            this.camera_name = camera_name;
            this.pixel_format = pixel_format;
            this.quality = quality;
        }

        public static GetSpotCameraRequest Deserialize(MessageDeserializer deserializer) => new GetSpotCameraRequest(deserializer);

        private GetSpotCameraRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.camera_name);
            deserializer.Read(out this.pixel_format);
            deserializer.Read(out this.quality);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.camera_name);
            serializer.Write(this.pixel_format);
            serializer.Write(this.quality);
        }

        public override string ToString()
        {
            return "GetSpotCameraRequest: " +
            "\ncamera_name: " + camera_name.ToString() +
            "\npixel_format: " + pixel_format.ToString() +
            "\nquality: " + quality.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
