//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class TransformRecordingServiceInfoRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/TransformRecordingServiceInfo";
        public override string RosMessageName => k_RosMessageName;

        public bool should_start_recording;

        public TransformRecordingServiceInfoRequest()
        {
            this.should_start_recording = false;
        }

        public TransformRecordingServiceInfoRequest(bool should_start_recording)
        {
            this.should_start_recording = should_start_recording;
        }

        public static TransformRecordingServiceInfoRequest Deserialize(MessageDeserializer deserializer) => new TransformRecordingServiceInfoRequest(deserializer);

        private TransformRecordingServiceInfoRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.should_start_recording);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.should_start_recording);
        }

        public override string ToString()
        {
            return "TransformRecordingServiceInfoRequest: " +
            "\nshould_start_recording: " + should_start_recording.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
